Repository peymanshahmarimikaeeldarehsi/duck-duck-clone, pull requests merged in 2020-10, with the labels that each got.

#6 Search bar
  duckduckgo-logo.png
  index.html
  style.css
Labels: design, enhancement

#10 made changes to improve code for search bar
  index.html
  style.css
Labels: enhancement

#11 made changes to search bar code
  index.html
  style.css
Labels: enhancement

#13 add navbar and update
  css/flexboxgrid.css
  css/font-awesome.css
  css/style.css
  fonts/FontAwesome.otf
  fonts/fontawesome-webfont.eot
  fonts/fontawesome-webfont.svg
  fonts/fontawesome-webfont.ttf
  fonts/fontawesome-webfont.woff
  fonts/fontawesome-webfont.woff2
  index.html
Labels: design

#18 update html and css
  css/style.css
  index.html
Labels: update
